/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Contact } from './contact';


export interface Account { 
    /**
     * Account Id
     */
    accountId: string;
    /**
     * Organization Id
     */
    orgId: string;
    /**
     * Account Name
     */
    accountName: string;
    contact: Contact;
    /**
     * Payment provider ID
     */
    paymentProviderId: string;
    /**
     * Created at
     */
    createdAt: string;
}

