/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactAddress { 
    /**
     * First line of the address.
     */
    addressLineOne: string;
    /**
     * Second line of the address.
     */
    addressLineTwo?: string;
    /**
     * City the address is in.
     */
    city: string;
    /**
     * State/Province the address is in.
     */
    province: string;
    /**
     * Post code of the address.
     */
    postalCode: string;
    /**
     * Country the address is in.
     */
    country: string;
}

