/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactAdd200ResponseAllOfDataInner { 
    accountName?: string | null;
    companyName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    /**
     * Phone number in E.164 phone number format (assumed +1 if no international code provided)
     */
    phoneNumber?: string | null;
    /**
     * Mobile number in E.164 phone number format (assumed +1 if no international code provided)
     */
    mobileNumber?: string | null;
    email?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    /**
     * A correctly formatted zip/postal code to match the country
     */
    zipCode?: string | null;
}

