/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactAddress } from './contactAddress';


export interface Contact { 
    /**
     * Contact Id
     */
    contactId: string;
    /**
     * Organization Id
     */
    orgId: string;
    /**
     * Contact email
     */
    email?: string;
    /**
     * First name
     */
    firstName: string;
    /**
     * Middle name
     */
    middleInitial?: string;
    /**
     * Last name
     */
    lastName: string;
    imageUrl: string;
    /**
     * Phone number
     */
    phoneNumber?: string;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Fax number
     */
    faxNumber?: string;
    address: ContactAddress;
}

