/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeeAdd200ResponseAllOfDataInner { 
    feeName?: string | null;
    rateType?: FeeAdd200ResponseAllOfDataInner.RateTypeEnum | null;
    /**
     * For fixedRate, an amount in the smallest denomination (e.g. cents/pence)
     */
    amount?: number | null;
}
export namespace FeeAdd200ResponseAllOfDataInner {
    export type RateTypeEnum = 'percentage' | 'fixedRate';
    export const RateTypeEnum = {
        Percentage: 'percentage' as RateTypeEnum,
        FixedRate: 'fixedRate' as RateTypeEnum
    };
}


