/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnitResponse } from './unitResponse';


export interface GetUnits200Response { 
    data?: Array<UnitResponse>;
    success?: boolean;
    error?: object;
}

