/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoveIn200ResponseAllOfDataInner { 
    accountName?: string | null;
    companyName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    unitName?: string | null;
    /**
     * A date in YYYY-MM-DD format
     */
    moveInDate?: string | null;
}

