/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PricingGroup { 
    id: string;
    groupName: string;
    dailyPrice: number;
    discount: number;
    promo: number;
    yearlyPrice: number;
    monthlyPrice: number;
    priceRaise: number;
}

