/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductAdd200ResponseAllOfDataInner { 
    itemName?: string | null;
    /**
     * Generated from the item name if not provided
     */
    itemDescription?: string | null;
    category?: string | null;
    /**
     * An amount in the smallest denomination (e.g. cents/pence)
     */
    price?: number | null;
    stockQuantity?: number | null;
    reorderLevel?: number | null;
}

