/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Report200ResponseAllOfDataInner } from './report200ResponseAllOfDataInner';


export interface Report200Response { 
    data: Array<Report200ResponseAllOfDataInner>;
    success: boolean;
    error: object;
}

