/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservationAdd200ResponseAllOfDataInner { 
    /**
     * A person\'s full name or a company
     */
    accountName?: string | null;
    companyName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    /**
     * There is no prescribed format
     */
    unitName?: string | null;
    width?: number | null;
    depth?: number | null;
    height?: number | null;
    features?: Array<string> | null;
    floor?: number | null;
}

