/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingsAppearance200ResponseAllOfDataInner { 
    theme?: SettingsAppearance200ResponseAllOfDataInner.ThemeEnum | null;
    /**
     * Color as a word
     */
    unitStatusColor?: string | null;
    showGrid?: boolean | null;
    showLabels?: boolean | null;
}
export namespace SettingsAppearance200ResponseAllOfDataInner {
    export type ThemeEnum = 'light' | 'dark';
    export const ThemeEnum = {
        Light: 'light' as ThemeEnum,
        Dark: 'dark' as ThemeEnum
    };
}


