/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingsOrganization200ResponseAllOfDataInner { 
    organizationName?: string | null;
    description?: string | null;
    currency?: string | null;
    daysBeforeLate?: number | null;
    daysBeforeLien?: number | null;
    daysBeforeOverlock?: number | null;
    daysBeforeMoveOut?: number | null;
    prorateMoveOutThreshold?: number | null;
    /**
     * Number of minutes
     */
    notificationDelay?: number | null;
    maxReminderAttempts?: number | null;
    billingCycleType?: SettingsOrganization200ResponseAllOfDataInner.BillingCycleTypeEnum | null;
    timezone?: SettingsOrganization200ResponseAllOfDataInner.TimezoneEnum | null;
}
export namespace SettingsOrganization200ResponseAllOfDataInner {
    export type BillingCycleTypeEnum = 'FIRST_OF_MONTH';
    export const BillingCycleTypeEnum = {
        FirstOfMonth: 'FIRST_OF_MONTH' as BillingCycleTypeEnum
    };
    export type TimezoneEnum = 'UTC';
    export const TimezoneEnum = {
        Utc: 'UTC' as TimezoneEnum
    };
}


