/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SmartAction = 'moveIn' | 'moveOut' | 'reserve' | 'invoices' | 'transactions';

export const SmartAction = {
    MoveIn: 'moveIn' as SmartAction,
    MoveOut: 'moveOut' as SmartAction,
    Reserve: 'reserve' as SmartAction,
    Invoices: 'invoices' as SmartAction,
    Transactions: 'transactions' as SmartAction
};

