/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmartResponseCompany { 
    /**
     * Company ID
     */
    companyId: string;
    /**
     * Company name
     */
    companyName: string;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Email
     */
    email: string | null;
}

