/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Action data
 */
export interface SmartResponseActionData { 
    /**
     * Date
     */
    date: string | null;
    /**
     * Account name
     */
    accountName: string | null;
}

