/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmartFeature } from './smartFeature';


export interface SmartResponseFilter { 
    /**
     * List of features to filter
     */
    features: Array<SmartFeature>;
    /**
     * List of floors to filter
     */
    floors: Array<SmartFeature>;
    /**
     * Minimum price
     */
    minPrice: number;
    /**
     * Maximum price
     */
    maxPrice: number;
    /**
     * Length
     */
    length: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number | null;
}

