/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmartResponseReservation { 
    /**
     * Reservation ID
     */
    reservationId: string;
    /**
     * Account name
     */
    accountName: string;
    /**
     * Unit ID
     */
    unitId: string;
    /**
     * Unit name
     */
    unitName: string;
}

