/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SmartResultType = 'company' | 'contact' | 'filter' | 'lease' | 'reservation' | 'unit' | 'unit-feature';

export const SmartResultType = {
    Company: 'company' as SmartResultType,
    Contact: 'contact' as SmartResultType,
    Filter: 'filter' as SmartResultType,
    Lease: 'lease' as SmartResultType,
    Reservation: 'reservation' as SmartResultType,
    Unit: 'unit' as SmartResultType,
    UnitFeature: 'unit-feature' as SmartResultType
};

