/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusFilters200ResponseAllOfDataInner { 
    available?: boolean | null;
    reserved?: boolean | null;
    occupied?: boolean | null;
    overlocked?: boolean | null;
    late?: boolean | null;
    auction?: boolean | null;
    lien?: boolean | null;
    futureBooked?: boolean | null;
}

