/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';


/**
 * Reservation details if the unit is reserved, null otherwise
 */
export interface UnitResponseUnitReservation { 
    unitReservationId: string;
    createdAt: string;
    createdBy: string;
    account: Account;
    expiresAt: string;
}

