/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemAttributeValue } from './systemAttributeValue';
import { CustomAttributeValue } from './customAttributeValue';


export interface UnitAttribute { 
    customAttributeValue: CustomAttributeValue | null;
    systemAttributeValue: SystemAttributeValue | null;
}

