/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Lease } from './lease';


export interface UnitSubscription { 
    unitId: string;
    moveInDate: string;
    leaseId: string;
    lease: Lease;
    account: Account;
    unitSubscriptionId: string;
}

